project:
  type: website
  resources: 
    - lectures/images/*
    - notebooks/*
  # pre-render:
  #     - python runfirst.py

website:

  page-navigation: true
  title: "EECE7398 Fall 2024"
  description: "Homepage EECS7398 - Special Topic: Compilers, Fall 2024."
  site-url: "https://normrubin.github.io/"
  repo-url: https://github.com/normrubin/normrubin.github.io
  repo-actions: [edit, issue]




  back-to-top-navigation: true

  open-graph: true

  page-footer:
    right: "This page is built with  [Quarto](https://quarto.org/)."
    left:  "[EECS 7398 website]( https://normrubin.github.io/)"
    background: "#D9E3E4"


  sidebar:
    background: "#D9E3E4"
    align: center
    style: "docked"
    contents:
      - text: EECS 7398
        contents:
          - text: Weekly Schedule
            file : "weekly.qmd"
          - text: "Course content"
          - text: "Blog Posts"
          - section: Homework
            auto: homeworks
          - text : "How to submit assignments"
            file : "Class_overview/What_to_do.qmd"
      - text: "Bril Documentation"
        href: "https://capra.cs.cornell.edu/bril/"
      - text: "Bril github"
        href: "https://github.com/normrubin/bril"






